# Generated by Django 6.0 on 2025-12-07 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_alter_attachment_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_at"]},
        ),
    ]
