# Generated by Django 6.0 on 2025-12-28 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_comment_options_attachment_upload_key_and_more'),
        ('comments', '0004_attachment_upload_key_alter_attachment_comment'),
    ]

    operations = [
    ]
